---
cluster:
  name: tower
  namespace: argo
  project: tower-ops
  repoURL: https://github.com/SJoon99/tower-k8s.git
  revision: ops
  ref: cluster

apps:
  karmada-members:
    enabled: true
    name: tower-karmada-members
    namespace: karmada-system
    project: tower-ops
    destination:
      name: tower
    source:
      repoURL: https://github.com/SJoon99/tower-k8s.git
      path: apps/karmada-members
      targetRevision: ops
      releaseName: karmada-members
    annotations:
      argocd.argoproj.io/sync-wave: "30"
    syncPolicy:
      automated:
        enabled: true
        selfHeal: true
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - SkipDryRunOnMissingResource=true

  smurfx-federation-poc:
    enabled: true
    name: tower-smurfx-federation-poc
    namespace: smurfx-poc
    project: tower-ops
    destination:
      name: karmada
    source:
      repoURL: https://github.com/BellTigerLee/smurfx-federation.git
      path: .
      targetRevision: main
      directory:
        recurse: true
        include: "{environments/poc/*.yaml,workloads/sample-http/*.yaml,policies/sample-http/*.yaml}"
    syncPolicy:
      automated:
        enabled: false
      syncOptions:
        - CreateNamespace=false
        - ServerSideApply=true
        - SkipDryRunOnMissingResource=true
