---
cluster:
  name: tower
  namespace: argo
  project: tower-ops
  repoURL: https://github.com/SJoon99/tower-k8s.git
  revision: ops
  ref: cluster

apps:
  karmada-members:
    enabled: true
    name: tower-karmada-members
    namespace: karmada-system
    project: tower-ops
    destination:
      name: tower
    source:
      repoURL: https://github.com/SJoon99/tower-k8s.git
      path: apps/karmada-members
      targetRevision: ops
      releaseName: karmada-members
    annotations:
      argocd.argoproj.io/sync-wave: "30"
    syncPolicy:
      automated:
        enabled: true
        selfHeal: true
        prune: false
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - SkipDryRunOnMissingResource=true

  scalex-federation:
    enabled: true
    name: tower-scalex-federation
    namespace: argo
    project: tower-ops
    destination:
      name: tower
    source:
      repoURL: https://github.com/SJoon99/scalex-federation.git
      path: bootstrap
      targetRevision: main
    annotations:
      argocd.argoproj.io/sync-wave: "40"
    syncPolicy:
      automated:
        enabled: true
        selfHeal: true
        prune: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
